import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export default function ResourcesPage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ito</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Spill the Tea Resources <sub> 🧋 </sub>
        </h1>


        <div className={styles.grid}>
          <a href="https://seattleu.instructure.com/courses/1600628" className={styles.card}>
            <h2> SU CS Department Canvas &rarr;</h2>
            <p>Resources to start, revise, or get feedback on your resumes.</p>
          </a>

          <a href="https://www.seattleu.edu/careerengagement/students--recent-graduates/" className={styles.card}>
            <h2> SU Career Engagement Office &rarr;</h2>
            <p> Get one-on-one coaching with everything and everything. 
                Their services include resume building, job searching, interview prep, and mock interviews. 
            </p>
          </a>
        </div>

      </main>
    </div>
  )
}
