import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function ContactsPage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ito</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Contact Me! <sub> 📱 </sub>
        </h1>

        <div className={styles.grid}>
          <a href="https://www.linkedin.com/in/isabel-t-ovalles/" className={styles.card}>
            <h2> LinkedIn &rarr;</h2>
            <p> Shoot me a message!</p>
          </a>

          <a href="" className={styles.card}>
            <h2> Email &rarr;</h2>
            <p> isabeltovalles@gmail.com </p>
          </a>
          </div> 
      </main>
    </div>
  )
}
