import Head from 'next/head'
//import Image from 'next/image'
import pfp from '../public/chibi_pfp.png'
import NextImage from "next/image";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>ito</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">
          Isabel T Ovalles <sub> 🧋 </sub>
        </h1>

        <NextImage
          src={pfp}
          alt="Chibi drawing of Isabel Ovalles drinking boba with a video game controller next to her"
          width={300}
          height={300}
          className="my-4 opacity-100"
        />
        
        <p className="description">
          gameplay engineer | su comp sci 23&apos; | sea &rarr; sf
        </p>

      </main>
    </div>
  )
}
